Task1
Rubsee/mentoring-first-task pull request #1
Opened 2024-11-09 17:01 UTC by Rubsee

Закончил выполнение 15ого задания  с localStorage

2024-12-06 13:50 UTC, krymnon69 commented on src/app/localstorage/localstorage.component.html
Лишние файлы

2024-12-06 13:50 UTC, krymnon69 commented on src/app/services/users-api.service.ts
> +
Зачем здесь пробел?

2024-12-06 13:50 UTC, krymnon69 commented on src/app/user-card/user-card.component.html
> +  <span>name: {{ user.name }} </span><br>
`<br>`

2024-12-06 13:50 UTC, bag1stan commented on src/app/user-card/user-card.component.html
> +  <span>name: {{ user.name }} </span><br>
Задача решается с помощью flex-direction

2024-12-06 13:50 UTC, krymnon69 commented on src/app/user-card/user-card.component.html
> +  </button>
```
<button (click)="onEdit()">
    Редактировать
</button>
```

2024-12-06 13:50 UTC, krymnon69 commented on src/app/users-list/edit-user-dialog/edit-user-dialog.component.ts
> +  form: FormGroup;
Здесь ты убил типизацию потому что form: `FormGroup<any>`

2024-12-06 13:50 UTC, krymnon69 commented on src/app/users-list/edit-user-dialog/edit-user-dialog.component.ts
> +  form: FormGroup;
```
FormGroup<{
   id: FormControl<null | number>;
   ....
}>
```

2024-12-06 13:50 UTC, krymnon69 commented on src/app/users-list/edit-user-dialog/edit-user-dialog.component.ts
> +  form: FormGroup;
readonly

2024-12-06 13:50 UTC, krymnon69 commented on src/app/users-list/edit-user-dialog/edit-user-dialog.component.ts
> +    @Inject(MAT_DIALOG_DATA) public data: { user: User; isEdit: boolean }
Забываешь readonly

2024-12-06 13:50 UTC, bag1stan commented on src/app/users-list/edit-user-dialog/edit-user-dialog.component.ts
> +    @Inject(MAT_DIALOG_DATA) public data: { user: User; isEdit: boolean }
```
export interface EditUserDialogData {
 user: User;
  isEdit: boolean 
  }
```

2024-12-06 13:50 UTC, krymnon69 commented on src/app/users-list/users-list.component.ts
> +    const dialogRef = this.dialog.open(EditUserDialogComponent, {
`open<EditUserDialogComponent, EditUserDialogData, User | null>`

2024-12-06 13:50 UTC, krymnon69 commented on src/app/users-list/edit-user-dialog/edit-user-dialog.component.ts
> +  form: FormGroup;
`this.form = this.getUserFormGroup();`

2024-12-06 13:50 UTC, krymnon69 commented on src/app/users-list/edit-user-dialog/edit-user-dialog.component.ts
> +      this.store.dispatch(UsersActions.generateNewId());
Это не требуется

2024-12-06 13:50 UTC, krymnon69 commented on src/app/users-list/edit-user-dialog/edit-user-dialog.component.ts
> +      });
Это не надо

2024-12-06 13:50 UTC, krymnon69 commented on src/app/users-list/edit-user-dialog/edit-user-dialog.component.ts
> +    void {
Форматирование

2024-12-06 13:50 UTC, krymnon69 commented on src/app/users-list/edit-user-dialog/edit-user-dialog.component.html
> +    <button mat-button type="button" (click)="onCancel()">Отмена</button>
`  <button mat-dialog-close>`

2024-12-06 13:50 UTC, krymnon69 commented on src/app/users-list/store/users.reducer.ts
> +const initialState: { users: User[], error: any, loading: boolean } = {
`interface State { 
users: User[], 
error: any, 
loading: boolean 
}`

2024-12-06 13:50 UTC, krymnon69 commented on src/app/users-list/store/users.reducer.ts
> +  on(UsersActions.set, (state, payload) => ({
`(state, { users })`

2024-12-06 13:50 UTC, krymnon69 commented on src/app/users-list/store/users.reducer.ts
> +      }
`state.users.map((user) => user.id === editedUser.id ? editedUser : user`

2024-12-06 13:50 UTC, krymnon69 commented on src/app/users-list/store/users.reducer.ts
> +    loading: false,
как правило используется loadingStatus: INIT | ERROR | LOADING | LOADED

2024-12-06 13:50 UTC, krymnon69 commented on src/app/users-list/store/users.selectors.ts
> +interface AppState {
Вот это здесь точно не должно быть

2024-12-06 13:50 UTC, krymnon69 commented on src/app/users-list/users-list.component.html
> +  (editUser)="onEditUser(user)">
`EventEmitter<void>`

2024-12-06 13:50 UTC, krymnon69 commented on src/app/users-list/users-list.component.html
> +<button class="user-list__button"
БЭМ

2024-12-06 13:50 UTC, krymnon69 commented on src/app/users-list/users-list.component.ts
> +        }))
Некорректное создание нового пользователя, данные введённые пользователем не используются и отправляются пустые строки

2024-12-06 13:50 UTC, krymnon69 commented on src/app/users-list/users-list.component.ts
> +  protected readonly selectUsers = selectUsers;
что это?

2024-12-11 13:36 UTC, krymnon69 commented on src/app/users-list/edit-user-dialog/edit-user-dialog.component.ts
> +    private dialogRef: MatDialogRef<EditUserDialogComponent>,
MatDialogRef<EditUserDialogComponent, User>,

2024-12-11 13:37 UTC, krymnon69 commented on src/app/users-list/edit-user-dialog/edit-user-dialog.component.ts
> +      this.dialogRef.close(this.form.value);
``` close({ ...this.data.user, this.form.getRawValue() })```

2024-12-11 13:44 UTC, krymnon69 commented on src/app/users-list/users-list.component.ts
> +            this.dialog.open<EditUserDialogComponent, EditUserDialogData, User | null>(EditUserDialogComponent, {
User | null !== Pick<User, 'name' | 'email' | 'address'>

2024-12-11 13:47 UTC, krymnon69 commented on src/app/users-list/users-list.component.ts
> +            this.dialog.open<EditUserDialogComponent, EditUserDialogData, User | null>(EditUserDialogComponent, {
Pick<User, 'name' | 'email' | 'address'> = interface {
  name: string,
  email: string,
  address: Address,
}

2024-12-11 13:48 UTC, krymnon69 commented on src/app/users-list/users-list.component.ts
> +            this.dialog.open<EditUserDialogComponent, EditUserDialogData, User | null>(EditUserDialogComponent, {
```
Omit<User, 'id' | 'geo' | 'phone' | 'website' | 'company'> = interface {
  name: string,
  email: string,
  address: Address,
}
```

2024-12-25 05:04 UTC, Rubsee commented
tg: @keyshio

2024-12-26 04:53 UTC, asylbekovkairat requested changes

2024-12-26 04:53 UTC, asylbekovkairat commented on src/app/app.config.ts
> +import {provideHttpClient} from '@angular/common/http';
нужно сортировка импортов 
VsCode 
ctrl+shift+p -> sort imports

2024-12-26 04:53 UTC, asylbekovkairat commented on src/app/app.config.ts
> +import {provideStoreDevtools} from '@ngrx/store-devtools';
слетело форматирование

2024-12-26 04:53 UTC, asylbekovkairat commented on src/app/interfaces/state.interface.ts
> +import {LoadingStatus} from "../enums/loading-status.enum";
слетело форматирование

2024-12-26 04:53 UTC, asylbekovkairat commented on src/app/interfaces/state.interface.ts
> +export interface State {
не корректное название для интерфейса, так как слово State имеет более обширное понятие, лучше написать с более точное конкретикой.

2024-12-26 04:53 UTC, asylbekovkairat commented on src/app/interfaces/user.interface.ts
> +// interface Company {
удалите комментарии

2024-12-26 04:53 UTC, asylbekovkairat commented on src/app/interfaces/user.interface.ts
> +  // geo: Geo,
удалите комментарии

2024-12-26 04:53 UTC, asylbekovkairat commented on src/app/localstorage/localstorage.component.ts
> +import {User} from '../interfaces/user.interface';
слетело форматирование

2024-12-26 04:53 UTC, asylbekovkairat commented on src/app/localstorage/localstorage.component.ts
> +        console.error('Ошибка при парсинге данных из localStorage', error);
удалите лог

2024-12-26 04:53 UTC, asylbekovkairat commented on src/app/localstorage/localstorage.component.ts
> +      console.error('Ошибка при сохранении данных в localStorage', error);
удалите лог, в catch он должен возвращать error

2024-12-26 04:53 UTC, asylbekovkairat commented on src/app/localstorage/localstorage.component.ts
> +  setUsers(users: User[]): void {
также является хорошей практикой указывать модификаторы доступа для методов класса тоже

2024-12-26 04:53 UTC, asylbekovkairat commented on src/app/services/users-api.service.ts
> +import {User} from "../interfaces/user.interface";
слетело форматирование

2024-12-26 04:53 UTC, asylbekovkairat commented on src/app/services/users-api.service.ts
> +    console.log('start')
удалите лог

2024-12-26 04:53 UTC, asylbekovkairat commented on src/app/user-card/user-card.component.ts
> +
удалите пустую строку

2024-12-26 04:53 UTC, asylbekovkairat commented on src/app/users-list/edit-user-dialog/edit-user-dialog.component.ts
> +import {NgIf} from "@angular/common";
слетело форматирование

2024-12-26 04:53 UTC, asylbekovkairat commented on src/app/users-list/edit-user-dialog/edit-user-dialog.component.ts
> +
удалите пустую строку

2024-12-26 04:53 UTC, asylbekovkairat commented on src/app/users-list/edit-user-dialog/edit-user-dialog.component.ts
> +    @Inject(MAT_DIALOG_DATA) public readonly data: EditUserDialogData,
для инжектирования можете использовать inject, изучите этот способ тоже

2024-12-26 04:53 UTC, asylbekovkairat commented on src/app/users-list/edit-user-dialog/edit-user-dialog.component.ts
> +      console.log(this.form.value);
удалите лог

2024-12-26 04:53 UTC, asylbekovkairat commented on src/app/users-list/store/users.effects.ts
> +    tap(() => console.log('Effect triggered: loadUsers')),
удалите лог

2024-12-26 04:53 UTC, asylbekovkairat commented on src/app/users-list/store/users.effects.ts
> +          console.error('API error: ', error);
удалите логи

2024-12-26 04:53 UTC, asylbekovkairat commented on src/app/users-list/store/users.reducer.ts
> +import {LoadingStatus} from "../../enums/loading-status.enum";
слетело форматирование

2024-12-26 04:53 UTC, asylbekovkairat commented on src/app/users-list/users-list.component.ts
> +        console.log(result)
удалите ненужные логи

2024-12-28 23:32 UTC, Rubsee commented on src/app/users-list/edit-user-dialog/edit-user-dialog.component.ts
>    MatDialogActions,
Не совсем понял, что не так с форматированием?

2024-12-29 12:59 UTC, asylbekovkairat requested changes

2024-12-29 12:59 UTC, asylbekovkairat commented on src/app/app.component.ts
> +  constructor() {
зачем пустой constructor? удалите

2024-12-31 02:49 UTC, asylbekovkairat requested changes

2024-12-31 02:49 UTC, asylbekovkairat commented on src/app/app.component.ts
> +  constructor() {}
зачем пустой constructor? можно удалить

2024-12-31 02:49 UTC, asylbekovkairat commented on src/app/interfaces/state.interface.ts
> +  error: any;
не используйте any, типизируйте

2024-12-31 02:49 UTC, asylbekovkairat commented on src/app/interfaces/userState.interface.ts
> +  error?: any;
не используйте any, типизируйте

2024-12-31 02:49 UTC, asylbekovkairat commented on src/app/services/users-api.service.ts
> +  readonly apiService = inject(HttpClient);
добавьте модификатор доступа

2024-12-31 02:49 UTC, asylbekovkairat commented on src/app/users-list/edit-user-dialog/edit-user-dialog.component.ts
>    MatDialogActions,
теперь гуд

2024-12-31 02:49 UTC, asylbekovkairat commented on src/app/users-list/edit-user-dialog/edit-user-dialog.component.ts
> +  readonly form = this.getUserFormGroup();
добавьте модификатор доступа

2024-12-31 02:49 UTC, asylbekovkairat commented on src/app/users-list/store/users.effects.ts
> +            console.error('API error: ', error);
удалите лог 

и можно сократить 
` catchError((error) =>of(UsersActions.loadUsersFailure({ error })))`

2024-12-31 02:49 UTC, asylbekovkairat commented on src/app/users-list/store/users.selectors.ts
> +  users: UserState;
название не корректное, (см комм выше)

2025-01-03 03:53 UTC, asylbekovkairat requested changes

2025-01-03 03:53 UTC, asylbekovkairat commented on src/app/interfaces/usersSelectorState.interface.ts
> +  error?: any;
не используйте any

2025-01-03 03:53 UTC, asylbekovkairat commented on src/app/localstorage/localstorage.component.ts
> +      try {
зачем здесь try catch конструкция? можно без нее написать

2025-01-03 03:53 UTC, asylbekovkairat commented on src/app/localstorage/localstorage.component.ts
> +    try {
try catch не нужен

2025-01-03 03:53 UTC, asylbekovkairat commented on src/app/users-list/store/users.effects.ts
> +          catchError((error) => {
Давайте посмотрим, как можно более лаконично написать код ниже
` catchError((error) => {
            return of(UsersActions.loadUsersFailure({ error }));
          })`
          
  Мы видим что после стрелки (=>) у нас идет фигурные скобки, которые открывают тело функции и в return мы возвращаем, лишь одну функцию. Данный код, можно облегчить, так: 
  `catchError((error) => of(UsersActions.loadUsersFailure({ error })))`
  стрелка в стрелочных функция и так является заменой для return. 
  
  Но учтите, так работает если код можно вмести в одну строку, если кода больше, чем на одну строку, то нужно открывать тело функции

2025-01-04 10:39 UTC, asylbekovkairat requested changes

2025-01-04 10:39 UTC, asylbekovkairat commented on src/index.html
> +
удалите пустую строку

2025-06-16 15:18 UTC, merged